server:
# Setting Port to 0 causes spring boot to randomise the port
  port: 0
shell:
  ssh:
    port: 2032
security:
  basic:
    enabled: false
spring:
  data:
    cassandra:
      keyspace-name: bell_sam
      # hostname of your Cassandra Docker instance
      contact-points: bellsam_cassandra_1
      port: 9042